spring:
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

cloud:
  aws:
    s3:
      bucket: ${Bucket-Name}
    credentials:
      access-key: ${IAM-Access-Key}
      secret-key: ${IAM-Secret-Key}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

springdoc:
  default-produces-media-type: application/json

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.rest1: DEBUG
